name: flutter_provide_mobx_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^0.2.0
  flutter_mobx: ^0.2.0+1
  # provide: ^1.0.2
  provider: ^2.0.1+1
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.1
  mobx_codegen: ^0.2.0+1

flutter:
  uses-material-design: true
